import ScrollContainer from "@/components/ScrollContainer";
import { TERMS_VERSION, TERMS_EFFECTIVE_DATE } from "@/lib/legal";

export const metadata = {
  title: "Terms of Service — DreamScribe",
  description:
    "Terms of Service for DreamScribe, operated by Dharma Universal Inc.",
};

export default function TermsPage() {
  return (
    <div className="pt-[110px] pb-20 w-full flex flex-col items-center">
      <div
        className="w-[min(820px,98vw)]"
        style={{ opacity: 0, animation: "ember-in 1.5s ease forwards 0.2s" }}
      >
        <ScrollContainer>
          <div className="relative z-[2] text-ink-sepia font-cormorant">
            <h1 className="font-pinyon text-[2.8rem] mb-2 text-center">
              Terms of Service
            </h1>
            <p className="font-fell italic text-center text-[0.85rem] mb-1 opacity-80">
              DreamScribe — operated by Dharma Universal Inc.
            </p>
            <p className="font-fell italic text-center text-[0.75rem] mb-8 opacity-70">
              Effective date: {TERMS_EFFECTIVE_DATE} · Version {TERMS_VERSION}
            </p>

            <div className="space-y-6 text-[1rem] leading-[1.7] max-w-[700px] mx-auto">
              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  1. Agreement to terms
                </h2>
                <p>
                  These Terms of Service (&ldquo;Terms&rdquo;) form a binding
                  legal agreement between you and{" "}
                  <strong>Dharma Universal Inc.</strong>, a California
                  corporation (&ldquo;DreamScribe,&rdquo; &ldquo;we,&rdquo;
                  &ldquo;us,&rdquo; or &ldquo;our&rdquo;), governing your
                  access to and use of the DreamScribe service at{" "}
                  <strong>dreamscribe.ai</strong> (the &ldquo;Service&rdquo;).
                </p>
                <p className="mt-2">
                  By creating an account, accessing, or using the Service, you
                  confirm that you have read, understood, and agree to be
                  bound by these Terms and our{" "}
                  <a href="/privacy" className="underline hover:text-amber">
                    Privacy Policy
                  </a>
                  . If you do not agree, do not use the Service.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  2. What DreamScribe is
                </h2>
                <p>
                  DreamScribe is a voice-first journaling platform that uses
                  artificial intelligence to:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>Record audio entries (&ldquo;Scribes&rdquo;).</li>
                  <li>
                    Transcribe audio into text using OpenAI&apos;s open-source
                    Whisper model.
                  </li>
                  <li>
                    Generate brain region activation scores from your audio
                    using Meta&apos;s open-source TRIBE v2 model. These scores
                    are statistical model outputs, not medical measurements.
                  </li>
                  <li>
                    Generate personalized text insights using Anthropic&apos;s
                    Claude AI model.
                  </li>
                  <li>
                    Detect patterns across your entries through our internal
                    Ember AI agent and the Mnemo observability layer.
                  </li>
                  <li>
                    Allow you to share entries publicly on the Bonfire feed,
                    follow other users, send messages to mutual followers,
                    star public entries, and comment.
                  </li>
                </ul>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  3. NOT MEDICAL OR MENTAL HEALTH ADVICE
                </h2>
                <p>
                  <strong>
                    DreamScribe is not a medical, mental health, therapy, or
                    healthcare service.
                  </strong>{" "}
                  Brain activation scores generated by TRIBE v2 are
                  statistical predictions from an AI model. They are not
                  diagnoses, do not measure your actual brain, and do not
                  constitute medical information. The text insights generated
                  by Claude AI are not therapy, counseling, medical advice,
                  legal advice, or professional advice of any kind.
                </p>
                <p className="mt-2">
                  Do not rely on DreamScribe for any decision related to your
                  physical or mental health. If you are experiencing a mental
                  health emergency, suicidal thoughts, or crisis, contact a
                  qualified professional or call <strong>988</strong> (Suicide
                  & Crisis Lifeline) in the United States, or your local
                  emergency services.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  4. Eligibility
                </h2>
                <p>
                  You must be at least <strong>18 years old</strong> to use
                  DreamScribe. By creating an account, you represent and
                  warrant that you are 18 or older, that the information you
                  provide is accurate, and that you have the legal capacity to
                  enter into these Terms.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  5. Your account
                </h2>
                <p>
                  You are responsible for keeping your login credentials
                  secure and for all activity that occurs on your account.
                  Notify us immediately at{" "}
                  <strong>dharma@dharmauniversal.ai</strong> if you suspect
                  unauthorized access.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  6. Your content
                </h2>
                <p>
                  You retain all ownership rights to the audio recordings,
                  transcripts, comments, and other content you submit
                  (&ldquo;Your Content&rdquo;). By submitting Your Content,
                  you grant DreamScribe a worldwide, royalty-free, non-exclusive
                  license to host, store, process, transmit, transcribe,
                  analyze with AI, display (only as you choose to share it),
                  and generate derivative outputs (such as transcripts,
                  scores, and insights) solely to provide the Service to you.
                </p>
                <p className="mt-2">
                  When you mark an entry as &ldquo;public,&rdquo; you grant a
                  separate, additional license for other authenticated
                  DreamScribe users to view and interact with that entry
                  (star, comment) on the Bonfire feed and on your public
                  profile until you change it back to private or delete it.
                </p>
                <p className="mt-2">
                  You represent that Your Content does not infringe any third
                  party&apos;s rights, does not contain unlawful content, and
                  is not intended to harass, defame, or threaten any person.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  7. Acceptable use
                </h2>
                <p>You agree not to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>
                    Use the Service for unlawful purposes or in violation of
                    these Terms.
                  </li>
                  <li>
                    Upload content that is illegal, defamatory, harassing,
                    obscene, sexually explicit involving minors, or that
                    infringes intellectual property rights.
                  </li>
                  <li>
                    Impersonate any person or misrepresent your affiliation.
                  </li>
                  <li>
                    Attempt to access another user&apos;s account, scrape the
                    Service, reverse-engineer the AI models, or interfere with
                    the Service&apos;s operation.
                  </li>
                  <li>
                    Use the Service to provide medical, mental health, legal,
                    or financial advice to others.
                  </li>
                  <li>
                    Use any Bonfire content (other users&apos; public entries)
                    for commercial purposes, training AI models, scraping, or
                    redistribution.
                  </li>
                </ul>
                <p className="mt-2">
                  We may suspend or terminate your account at any time, with
                  or without notice, for any violation of these Terms.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  8. AI processing acknowledgment
                </h2>
                <p>
                  You acknowledge and consent that your voice recordings, the
                  text transcripts derived from them, and brain activation
                  scores will be processed by automated AI systems including:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>
                    <strong>OpenAI Whisper</strong> (open source) for
                    transcription.
                  </li>
                  <li>
                    <strong>Meta TRIBE v2</strong> (open source) for brain
                    region activation analysis.
                  </li>
                  <li>
                    <strong>Anthropic Claude</strong> for personalized text
                    insights.
                  </li>
                  <li>
                    <strong>Mnemo</strong> for AI agent memory and
                    observability.
                  </li>
                </ul>
                <p className="mt-2">
                  See our{" "}
                  <a href="/privacy" className="underline hover:text-amber">
                    Privacy Policy
                  </a>{" "}
                  for full details on how data flows through these systems.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  9. Intellectual property
                </h2>
                <p>
                  The Service, including all design, code, branding, the
                  &ldquo;DreamScribe&rdquo; name, the candlelit aesthetic, and
                  the Ember AI agent are owned by Dharma Universal Inc. and
                  protected by U.S. and international copyright, trademark,
                  and other intellectual property laws. You may not copy,
                  reproduce, or create derivative works of the Service without
                  our written permission.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  10. Disclaimers
                </h2>
                <p className="uppercase">
                  THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
                  AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER
                  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED
                  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
                  PURPOSE, NON-INFRINGEMENT, ACCURACY, OR THAT THE SERVICE
                  WILL BE UNINTERRUPTED OR ERROR-FREE.
                </p>
                <p className="mt-2 uppercase">
                  AI-GENERATED CONTENT (TRANSCRIPTS, BRAIN SCORES, INSIGHTS,
                  PATTERNS) MAY CONTAIN ERRORS, INACCURACIES, OR HALLUCINATIONS.
                  YOU USE IT AT YOUR OWN RISK.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  11. Limitation of liability
                </h2>
                <p className="uppercase">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, DHARMA UNIVERSAL
                  INC., ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS WILL
                  NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
                  CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS,
                  REVENUE, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING
                  FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF
                  WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                </p>
                <p className="mt-2 uppercase">
                  OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIMS ARISING OUT OF
                  OR RELATED TO THE SERVICE OR THESE TERMS WILL NOT EXCEED THE
                  GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS
                  PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS
                  ($100.00).
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  12. Indemnification
                </h2>
                <p>
                  You agree to indemnify, defend, and hold harmless Dharma
                  Universal Inc. and its officers, directors, employees, and
                  agents from and against any claims, liabilities, damages,
                  losses, and expenses (including reasonable attorneys&apos;
                  fees) arising out of or in any way connected with (a) Your
                  Content, (b) your use or misuse of the Service, (c) your
                  violation of these Terms, or (d) your violation of any
                  rights of any third party.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  13. Termination
                </h2>
                <p>
                  You may stop using DreamScribe and delete your account at
                  any time. We may suspend or terminate your access to the
                  Service at any time, with or without notice, for any reason,
                  including violation of these Terms. Sections 6, 9, 10, 11,
                  12, 14, and 15 will survive termination.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  14. Governing law and dispute resolution
                </h2>
                <p>
                  These Terms are governed by the laws of the State of
                  California, without regard to its conflict-of-laws rules.
                  Any dispute arising from these Terms or the Service will be
                  resolved exclusively by binding arbitration administered by
                  the American Arbitration Association under its Consumer
                  Arbitration Rules, in San Francisco, California, except
                  that you may bring claims in small claims court if eligible.
                </p>
                <p className="mt-2 uppercase">
                  You and DreamScribe agree that any dispute will be brought
                  on an individual basis only. Class actions and class
                  arbitrations are waived.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  15. Changes to these terms
                </h2>
                <p>
                  We may update these Terms from time to time. When we make
                  material changes, we will update the version and effective
                  date above and provide notice in-app or by email. Your
                  continued use of the Service after changes means you accept
                  the new Terms.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  16. Contact
                </h2>
                <p>
                  Dharma Universal Inc.
                  <br />
                  DreamScribe Legal
                  <br />
                  Email: <strong>dharma@dharmauniversal.ai</strong>
                  <br />
                  Website: <strong>https://dreamscribe.ai</strong>
                </p>
              </section>
            </div>
          </div>
        </ScrollContainer>
      </div>
    </div>
  );
}
