import ScrollContainer from "@/components/ScrollContainer";
import { PRIVACY_VERSION, PRIVACY_EFFECTIVE_DATE } from "@/lib/legal";

export const metadata = {
  title: "Privacy Policy — DreamScribe",
  description:
    "How DreamScribe (Dharma Universal Inc.) collects, uses, and protects your data, including voice recordings, brain activation data, and AI-generated insights.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="pt-[110px] pb-20 w-full flex flex-col items-center">
      <div
        className="w-[min(820px,98vw)]"
        style={{ opacity: 0, animation: "ember-in 1.5s ease forwards 0.2s" }}
      >
        <ScrollContainer>
          <div className="relative z-[2] text-ink-sepia font-cormorant">
            <h1 className="font-pinyon text-[2.8rem] mb-2 text-center">
              Privacy Policy
            </h1>
            <p className="font-fell italic text-center text-[0.85rem] mb-1 opacity-80">
              DreamScribe — operated by Dharma Universal Inc.
            </p>
            <p className="font-fell italic text-center text-[0.75rem] mb-8 opacity-70">
              Effective date: {PRIVACY_EFFECTIVE_DATE} · Version{" "}
              {PRIVACY_VERSION}
            </p>

            <div className="space-y-6 text-[1rem] leading-[1.7] max-w-[700px] mx-auto">
              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  1. Who we are
                </h2>
                <p>
                  DreamScribe is a voice-first neural journal operated by{" "}
                  <strong>Dharma Universal Inc.</strong> (&ldquo;DreamScribe,&rdquo;
                  &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), a
                  California corporation. The service is accessed through{" "}
                  <strong>dreamscribe.ai</strong>. This Privacy Policy explains
                  what personal information we collect, how we use it, who we
                  share it with, your rights, and how to contact us.
                </p>
                <p className="mt-2">
                  By creating an account or using DreamScribe, you agree to
                  this Privacy Policy. If you do not agree, do not use the
                  service.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  2. What data we collect
                </h2>
                <p>We collect the following categories of personal data:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>
                    <strong>Account data:</strong> email, username, display
                    name, chosen archetype, profile photo, bio.
                  </li>
                  <li>
                    <strong>Voice recordings:</strong> the raw audio you record
                    in your dream and daily journal entries.
                  </li>
                  <li>
                    <strong>Transcripts:</strong> the text of your spoken
                    journal entries, generated by automated speech-to-text.
                  </li>
                  <li>
                    <strong>Neural activation scores:</strong> brain region
                    activation values inferred from your audio by the TRIBE v2
                    model. These are statistical model outputs, not medical
                    measurements.
                  </li>
                  <li>
                    <strong>AI-generated insights:</strong> personalized
                    interpretations and pattern observations written by Anthropic
                    Claude based on your transcripts and scores.
                  </li>
                  <li>
                    <strong>Social activity:</strong> follows, stars, comments,
                    direct messages, and notifications.
                  </li>
                  <li>
                    <strong>Usage data:</strong> pages visited, features used,
                    timestamps, browser type, device type, and approximate IP
                    location.
                  </li>
                </ul>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  3. How your data is processed
                </h2>
                <p>
                  When you record a journal entry, the audio file is uploaded to
                  our private storage and then processed by an automated AI
                  pipeline. This is what happens, in order:
                </p>
                <ol className="list-decimal pl-6 mt-2 space-y-1">
                  <li>
                    Your audio is converted to MP3 by an internal ffmpeg process.
                  </li>
                  <li>
                    The audio is sent to <strong>OpenAI Whisper</strong>{" "}
                    (running locally on our servers) to produce a text
                    transcript.
                  </li>
                  <li>
                    The audio is processed by{" "}
                    <strong>Meta&apos;s TRIBE v2 model</strong>{" "}
                    (facebook/tribev2 from Hugging Face) to generate brain
                    region activation scores. These are statistical predictions,
                    not real brain measurements, and are not medical
                    diagnostics.
                  </li>
                  <li>
                    The transcript and brain scores are sent to{" "}
                    <strong>Anthropic Claude</strong> (claude-sonnet-4) which
                    generates a personalized text insight.
                  </li>
                  <li>
                    The transcript, scores, and insight are saved to your
                    DreamScribe account in our <strong>Supabase</strong>{" "}
                    database.
                  </li>
                  <li>
                    A trace of the AI run is logged to <strong>Mnemo</strong>{" "}
                    (our AI observability layer) so the Ember pattern-detection
                    agent can recognize patterns across your entries over time.
                  </li>
                </ol>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  4. Third parties we share data with
                </h2>
                <p>
                  To deliver the service, we share the data above with the
                  following processors. Each processor receives only what is
                  necessary to perform its function and is bound by its own
                  privacy commitments:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>
                    <strong>Anthropic, PBC</strong> — receives transcripts,
                    brain activation scores, mood labels, and your past journal
                    summaries to generate Claude AI insights.
                  </li>
                  <li>
                    <strong>Meta Platforms, Inc. (TRIBE v2)</strong> — the
                    TRIBE v2 model is open-source from Meta and runs on our
                    cloud infrastructure. Meta does not directly receive your
                    audio.
                  </li>
                  <li>
                    <strong>OpenAI Whisper</strong> — used as an open-source
                    model running on our servers; OpenAI does not directly
                    receive your audio.
                  </li>
                  <li>
                    <strong>Supabase Inc.</strong> — hosts our database and
                    audio file storage.
                  </li>
                  <li>
                    <strong>Modal Labs</strong> — runs our serverless backend
                    and AI processing pipeline.
                  </li>
                  <li>
                    <strong>Mnemo (usemnemo.com)</strong> — receives anonymized
                    agent traces, brain score summaries, and metadata for
                    pattern detection and AI observability.
                  </li>
                  <li>
                    <strong>Vercel Inc.</strong> — hosts our website and
                    serves our front end.
                  </li>
                </ul>
                <p className="mt-2">
                  We do <strong>not</strong> sell your personal data. We do not
                  share your voice recordings with advertisers, data brokers,
                  or marketers.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  5. Public vs private content
                </h2>
                <p>
                  Every journal entry defaults to <strong>private</strong>. You
                  can choose to mark an entry as public, in which case it will
                  appear in the global Bonfire feed and on your public profile.
                  You can revert any entry to private at any time. Comments and
                  stars on public entries are visible to other authenticated
                  users.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  6. Your rights — California residents (CCPA/CPRA)
                </h2>
                <p>
                  If you are a California resident, the California Consumer
                  Privacy Act (as amended by the CPRA) gives you specific
                  rights:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>
                    <strong>Right to know:</strong> request a copy of the
                    personal information we hold about you.
                  </li>
                  <li>
                    <strong>Right to delete:</strong> request that we delete
                    your account and personal data.
                  </li>
                  <li>
                    <strong>Right to correct:</strong> ask us to fix inaccurate
                    information.
                  </li>
                  <li>
                    <strong>Right to opt out of &ldquo;sale&rdquo; or
                    &ldquo;sharing&rdquo;:</strong> we do not sell or share
                    your data for cross-context behavioral advertising.
                  </li>
                  <li>
                    <strong>Right to limit use of sensitive personal
                    information:</strong> voice recordings are sensitive
                    information; you may delete them at any time.
                  </li>
                  <li>
                    <strong>Right to non-discrimination:</strong> we will not
                    deny service or charge differently if you exercise these
                    rights.
                  </li>
                </ul>
                <p className="mt-2">
                  To exercise any of these rights, contact us at{" "}
                  <strong>dharma@dharmauniversal.ai</strong>.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  7. Other privacy laws
                </h2>
                <p>
                  We make a good-faith effort to honor similar rights under
                  other applicable laws, including the EU&apos;s GDPR, the
                  Virginia CDPA, the Colorado CPA, the Connecticut CTDPA, the
                  Utah UCPA, and Canada&apos;s PIPEDA. Residents of those
                  jurisdictions may also contact us at{" "}
                  <strong>dharma@dharmauniversal.ai</strong>.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  8. Data retention
                </h2>
                <p>
                  We keep your data for as long as your account is active.
                  When you delete your account, we delete your audio files,
                  transcripts, brain scores, insights, comments, and profile
                  data within 30 days. Some logs and audit records may be
                  retained for up to 12 months for security and legal
                  compliance.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  9. Security
                </h2>
                <p>
                  We use industry-standard encryption in transit (HTTPS/TLS)
                  and at rest. Audio files are stored in a private storage
                  bucket and accessed via short-lived signed URLs. Passwords
                  are hashed by Supabase Auth. Despite reasonable safeguards,
                  no internet service can be 100% secure. You use DreamScribe
                  at your own risk.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  10. Children
                </h2>
                <p>
                  DreamScribe is intended for users <strong>18 and older</strong>.
                  We do not knowingly collect data from anyone under 18. If you
                  believe a minor has created an account, contact{" "}
                  <strong>dharma@dharmauniversal.ai</strong> and we will remove
                  the account and associated data.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  11. Important: not medical advice
                </h2>
                <p>
                  DreamScribe is not a medical or mental health service. Brain
                  activation scores are statistical model outputs, not
                  diagnoses. Claude AI insights are generated by an AI language
                  model and are not professional advice. If you are
                  experiencing a mental health emergency or thoughts of
                  self-harm, please contact a qualified professional or call
                  988 (Suicide & Crisis Lifeline) in the United States, or
                  your local emergency services.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  12. Changes to this policy
                </h2>
                <p>
                  We may update this Privacy Policy from time to time. When we
                  do, we will post the new version here, update the version
                  number and effective date, and where appropriate, notify you
                  by email or in-app notice. Continued use of DreamScribe
                  after changes means you accept the updated policy.
                </p>
              </section>

              <section>
                <h2 className="font-pinyon text-[1.6rem] mb-2">
                  13. Contact us
                </h2>
                <p>
                  Dharma Universal Inc.
                  <br />
                  DreamScribe Privacy Office
                  <br />
                  Email: <strong>dharma@dharmauniversal.ai</strong>
                  <br />
                  Website: <strong>https://dreamscribe.ai</strong>
                </p>
              </section>
            </div>
          </div>
        </ScrollContainer>
      </div>
    </div>
  );
}
